name: Prueba

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: springuser
          POSTGRES_PASSWORD: 12345
          POSTGRES_DB: springdb
        ports:
          - 5432:5432

    steps:
      - name: Haciendo Checkout
        uses: actions/checkout@v3

      - name: Ajustando el JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17.x
          distribution: adopt
          cache: maven

      - name: Hacer build con Maven
        run: mvn --batch-mode --update-snapshots clean package

      - name: Ejecutar las pruebas unitarias
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/springdb
          SPRING_DATASOURCE_USERNAME: springuser
          SPRING_DATASOURCE_PASSWORD: 12345
        run: mvn --batch-mode test

      - name: Generar el reporte Surefire
        run: mvn surefire-report:report

      - name: Copia el reporte Surefire HTML al repositorio
        run: |
          mkdir -p reports
          cp -r target/surefire-reports/* reports/
        if: always()

      - name: Copia el reporte HTML de Surefire al repositorio
        uses: actions/upload-artifact@v3
        with:
          name: Reporte Surefire HTML
          path: target/site/surefire-report.html

